[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Remove external_node_modules since we're using built-in fetch

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables for production
[context.production.environment]
  NODE_VERSION = "18"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  NODE_VERSION = "18"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  NODE_VERSION = "18"
